 export const employeesData = [
      {
        id: 1,
        firstName: 'Bob',
        lastName: 'Eponge',
        startDate: '03/09/2023',
        department: 'Human Resources',
        dateOfBirth: '03/06/2000',
        street: 'Rainbow street',
        city: 'San Francisco',
        state: 'California',
        abbreviation: 'CA',
        zipCode: '12345'
        },    
        {
        id: 2,
        firstName: 'Mickey',
        lastName: 'Mouse',
        startDate: '02/24/2021',
        department: 'Sales',
        dateOfBirth: '11/16/1988',
        street: 'Disneyland',
        city: 'Orlando',
        state: 'Florida',
        abbreviation: 'FL',
        zipCode: '67891'
        },
        {
        id: 3,
        firstName: 'Peter3',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 4,
        firstName: 'Peter4',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 5,
        firstName: 'Peter5',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 6,
        firstName: 'Peter6',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 7,
        firstName: 'Peter7',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 8,
        firstName: 'Peter8',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 9,
        firstName: 'Peter9',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 10,
        firstName: 'Peter10',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 11,
        firstName: 'Peter11',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        },
        {
        id: 12,
        firstName: 'Peter12',
        lastName: 'Pan',
        startDate: '12/01/2022',
        department: 'Marketing',
        dateOfBirth: '08/19/1997',
        street: 'Neverland',
        city: 'Honolulu',
        state: 'Hawaii',
        abbreviation: 'HI',
        zipCode: '54321'
        }
        
    ]